### ISSUE TITLE
error occurs when unicode search

### ISSUE THREAD

**Issue by malongge** [and3rson/django-searchable-select#2]
error log:

```
Internal Server Error: /searchableselect/filter
Traceback (most recent call last):
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\searchableselect\views.py", line 25, in filter_models
    in values
  File "C:\Anaconda3\envs\djangoadmin2\lib\site-packages\searchableselect\views.py", line 24, in <listcomp>
    for value
NameError: name 'unicode' is not defined

```

change 

`dict(pk=value.pk, name=unicode(value))` 

to 

```python
from django.utils.encoding import smart_str
... ...
dict(pk=value.pk, name=smart_str(value))
```
will be ok.

**Comment by and3rson** [comment]
@malongge Thank you for your report!
The fix is master now, I'm going to release 1.4.3.
